using Content.Shared.Ghost.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._DV.Administration.UI;

// Frontier: ghost role whitelist set
[GenerateTypedNameReferences]
public sealed partial class GhostRoleSetWhitelistPanel : PanelContainer
{
    public Action<ProtoId<GhostRolePrototype>, bool>? OnSetGhostRole;

    public GhostRoleSetWhitelistPanel(List<ProtoId<GhostRolePrototype>> ghostRoleList, string ghostRoleSetName, Color ghostRoleSetColor, IPrototypeManager proto, HashSet<ProtoId<GhostRolePrototype>> whitelists /*, bool globalWhitelist*/) // Aurora Song: Global whitelist forces all buttons on
    {
        RobustXamlLoader.Load(this);

        var allWhitelisted = true;
        foreach (var id in ghostRoleList)
        {
            var thisRole = id; // closure capturing funny
            var button = new CheckBox();
            button.Text = Loc.GetString(proto.Index(id).Name);
            button.Pressed = whitelists.Contains(id) /* || globalWhitelist*/; // Aurora Song: OR with globalWhitelist makes all buttons show checked
            button.OnPressed += _ => OnSetGhostRole?.Invoke(thisRole, button.Pressed); // Aurora Song: Calls OnSetGhostRole directly instead of OnButtonPressed which blocked changes
            RolesContainer.AddChild(button);

            allWhitelisted &= button.Pressed;
        }

        GhostRoleSet.Text = Loc.GetString(ghostRoleSetName);
        GhostRoleSet.Modulate = ghostRoleSetColor;
        GhostRoleSet.Pressed = allWhitelisted;
        GhostRoleSet.OnPressed += args => OnDepartmentPressed(ghostRoleList, whitelists /*, globalWhitelist*/); // Aurora Song: globalWhitelist parameter removed
    }

    // Aurora Song: Simplified ghost role set button handler - removed global whitelist logic
    private void OnDepartmentPressed(List<ProtoId<GhostRolePrototype>> ghostRoleList, HashSet<ProtoId<GhostRolePrototype>> whitelists)
    {
        foreach (var id in ghostRoleList)
        {
            // only request to whitelist roles that aren't already whitelisted, and vice versa
            if (whitelists.Contains(id) != GhostRoleSet.Pressed)
                OnSetGhostRole?.Invoke(id, GhostRoleSet.Pressed);
        }
    }

}
// End Frontier
