# Markings are inheriting. That means they can have parents now. Yay!

- type: marking
  abstract: true
  id: BaseColorWhite
  coloring:
    default:
      type:
        !type:SimpleColoring
          color: "#FFFFFF"

- type: marking
  abstract: true
  id: BaseTattoo
  coloring:
    default:
      type: !type:TattooColoring
      fallbackColor: "#666666"

- type: marking
  abstract: true
  id: BaseEyes
  bodyPart: Eyes
  markingCategory: Head
  coloring:
    default:
      type:
        !type:EyeColoring
          negative: true

- type: marking
  abstract: true
  id: BaseChest
  markingCategory: Chest
  bodyPart: Chest

- type: marking
  abstract: true
  id: BaseHead
  markingCategory: Head
  bodyPart: Head

- type: marking
  abstract: true
  id: BaseHeadTop
  markingCategory: HeadTop
  bodyPart: HeadTop

- type: marking
  abstract: true
  id: BaseHeadSide
  markingCategory: HeadSide
  bodyPart: HeadSide

- type: marking
  abstract: true
  id: BaseSnout
  markingCategory: Snout
  bodyPart: Snout

- type: marking
  abstract: true
  id: BaseTail
  markingCategory: Tail
  bodyPart: Tail

# Cyberlimbs
## (These are basic IPC parts, but they're also prosthetic markings for other species.)

## Exclude anything that doesn't have standard arms (e.g. harpies)
- type: marking
  abstract: true
  parent: BaseSpeciesIPC
  id: BaseArmsCyberlimb
  markingCategory: Arms
  invertSpeciesRestriction: true
  speciesRestriction:
  - Harpy
  - Vox
  - Diona

## Exclude anything that doesn't have standard legs (e.g. if any taurs are ever added)
- type: marking
  abstract: true
  parent: BaseSpeciesIPC
  id: BaseLegsCyberlimb
  markingCategory: Legs
  invertSpeciesRestriction: true
  speciesRestriction:
  - Harpy
  - Vox
  - Diona
