# Markings are inheriting. That means they can have parents now. Yay!

- type: marking
  abstract: true
  id: BaseTattoo
  coloring:
    default:
      type: !type:TattooColoring
      fallbackColor: "#666666"

- type: marking
  abstract: true
  id: BaseEyes
  bodyPart: Eyes
  markingCategory: Head
  coloring:
    default:
      type:
        !type:EyeColoring
          negative: true

- type: marking
  abstract: true
  id: BaseChest
  markingCategory: Chest
  bodyPart: Chest

- type: marking
  abstract: true
  id: BaseHead
  markingCategory: Head
  bodyPart: Head

- type: marking
  abstract: true
  id: BaseHeadTop
  markingCategory: HeadTop
  bodyPart: HeadTop

- type: marking
  abstract: true
  id: BaseHeadSide
  markingCategory: HeadSide
  bodyPart: HeadSide

- type: marking
  abstract: true
  id: BaseSnout
  markingCategory: Snout
  bodyPart: Snout

- type: marking
  abstract: true
  id: BaseTail
  markingCategory: Tail
  bodyPart: Tail
