// SPDX-FileCopyrightText: 2025 Ark
// SPDX-FileCopyrightText: 2025 ark1368
//
// SPDX-License-Identifier: MPL-2.0

// Copyright Rane (elijahrane@gmail.com) 2025
// All rights reserved. Relicensed under AGPL with permission

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Mono.FireControl;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Mono.FireControl.UI;

[GenerateTypedNameReferences]
public sealed partial class FireControlWindow : FancyWindow
{
    public FireControlNavControl Radar => NavRadar;
    public Action? OnServerRefresh;
    public Action? OnWeaponSelectionChanged;

    public readonly Dictionary<NetEntity, Button> WeaponsList = new();

    // Dictionary to store weapon name to entity mapping for easier filtering
    private readonly Dictionary<string, NetEntity> _weaponNameToEntity = new();

    // Weapon type filtering removed - ShipGunType not in Aurora

    private FireControlConsoleBoundInterfaceState? _currentState;
    public FireControlWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        RefreshButton.OnPressed += _ => OnServerRefresh?.Invoke();
        SelectAllButton.OnPressed += SelectAllWeapons;
        UnselectAllButton.OnPressed += UnselectAllWeapons;
        // Weapon type filter buttons not yet added to XAML
        //SelectBallisticButton.OnPressed += SelectBallisticWeapons;
        //SelectEnergyButton.OnPressed += SelectEnergyWeapons;
        //SelectMissileButton.OnPressed += SelectMissileWeapons;
    }

    private void SelectAllWeapons(BaseButton.ButtonEventArgs args)
    {
        foreach (var button in WeaponsList.Values)
        {
            button.Pressed = true;
        }

        OnWeaponSelectionChanged?.Invoke();

        UpdateAllWeaponButtonTexts();
    }

    private void UnselectAllWeapons(BaseButton.ButtonEventArgs args)
    {
        foreach (var button in WeaponsList.Values)
        {
            button.Pressed = false;
        }

        OnWeaponSelectionChanged?.Invoke();

        UpdateAllWeaponButtonTexts();
    }

    // Weapon type filtering disabled - ShipGunType not in Aurora
    private void SelectBallisticWeapons(BaseButton.ButtonEventArgs args)
    {
        // Select all weapons (no filtering available without ShipGunType)
        SelectAllWeapons(args);
    }

    private void SelectEnergyWeapons(BaseButton.ButtonEventArgs args)
    {
        // Select all weapons (no filtering available without ShipGunType)
        SelectAllWeapons(args);
    }

    private void SelectMissileWeapons(BaseButton.ButtonEventArgs args)
    {
        // Select all weapons (no filtering available without ShipGunType)
        SelectAllWeapons(args);
    }

    /// <summary>
    /// Updates the text of a weapon button based on its selection state and manual reload status.
    /// </summary>
    private void UpdateWeaponButtonText(Button button, FireControllableEntry controllable)
    {
        if (button.Pressed && controllable.HasManualReload && controllable.AmmoCount.HasValue)
        {
            button.Text = controllable.AmmoCount.Value.ToString();

            if (controllable.AmmoCount.Value == 0)
            {
                button.ModulateSelfOverride = Color.Red;
            }
            else
            {
                button.ModulateSelfOverride = null;
            }
        }
        else
        {
            button.Text = controllable.Name;
            button.ModulateSelfOverride = null;
        }
    }

    /// <summary>
    /// Updates all weapon button texts based on current selection state.
    /// </summary>
    private void UpdateAllWeaponButtonTexts()
    {
        foreach (var (netEntity, button) in WeaponsList)
        {
            var controllable = _currentState?.FireControllables?.FirstOrDefault(c => c.NetEntity == netEntity);

            if (controllable.HasValue)
            {
                UpdateWeaponButtonText(button, controllable.Value);
            }
        }
    }

    public void UpdateStatus(FireControlConsoleBoundInterfaceState state)
    {
        _currentState = state;
        NavRadar.UpdateState(state.NavState);

        if (state.Connected)
        {
            ServerStatus.Text = Loc.GetString("gunnery-window-connected");
            ServerStatus.FontColorOverride = Color.Green;
        }
        else
        {
            RefreshButton.Disabled = false;
            ServerStatus.Text = Loc.GetString("gunnery-window-disconnected");
            ServerStatus.FontColorOverride = Color.Red;
        }

        UpdateWeaponsList(state);

        UpdateAllWeaponButtonTexts();

        // Update the category buttons state based on whether weapons of that type are available
        // Weapon type filter buttons not yet added to XAML - commented out
        /*
        bool hasBallisticWeapons = false;
        bool hasEnergyWeapons = false;
        bool hasMissileWeapons = false;

        foreach (var kvp in _weaponTypes)
        {
            var type = kvp.Value;

            if (type == ShipGunType.Ballistic)
                hasBallisticWeapons = true;
            else if (type == ShipGunType.Energy)
                hasEnergyWeapons = true;
            else if (type == ShipGunType.Missile)
                hasMissileWeapons = true;

            if (hasBallisticWeapons && hasEnergyWeapons && hasMissileWeapons)
                break;
        }

        SelectBallisticButton.Disabled = !hasBallisticWeapons;
        SelectEnergyButton.Disabled = !hasEnergyWeapons;
        SelectMissileButton.Disabled = !hasMissileWeapons;
        */
    }

    private void UpdateWeaponsList(FireControlConsoleBoundInterfaceState state)
    {
        if (state.FireControllables == null)
        {
            WeaponsList.Clear();
            ControllablesBox.DisposeAllChildren();
            return;
        }

        var toRemove = new HashSet<NetEntity>(WeaponsList.Keys);

        foreach (var controllable in state.FireControllables)
        {
            if (WeaponsList.TryGetValue(controllable.NetEntity, out var existingButton))
            {
                toRemove.Remove(controllable.NetEntity);
                UpdateWeaponButtonText(existingButton, controllable);
            }
            else
            {
                var button = new Button
                {
                    ToggleMode = true,
                    Text = controllable.Name,
                    StyleClasses = { "ButtonSquare OpenRight" },
                    HorizontalExpand = true,
                    Margin = new Thickness(4, 1)
                };

                button.OnToggled += _ =>
                {
                    OnWeaponSelectionChanged?.Invoke();
                    UpdateAllWeaponButtonTexts();
                };

                ControllablesBox.AddChild(button);
                WeaponsList.Add(controllable.NetEntity, button);
                _weaponNameToEntity[controllable.Name] = controllable.NetEntity;
                // Note: ShipGunType tracking removed - weapon filter buttons not implemented in UI yet

                UpdateWeaponButtonText(button, controllable);
            }
        }

        foreach (var entity in toRemove)
        {
            if (WeaponsList.TryGetValue(entity, out var button))
            {
                ControllablesBox.RemoveChild(button);
                WeaponsList.Remove(entity);
            }
        }

        SelectAllButton.Disabled = WeaponsList.Count == 0;
        UnselectAllButton.Disabled = WeaponsList.Count == 0;
    }
}
