using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._AS.Contraband.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._AS.Contraband.UI;

[GenerateTypedNameReferences]
public sealed partial class ContrabandDatabaseMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly Dictionary<string, BoxContainer> _characterSections = new();
    private readonly Dictionary<string, Button> _characterToggles = new();

    public ContrabandDatabaseMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(ContrabandDatabaseState state)
    {
        ContentContainer.RemoveAllChildren();
        _characterSections.Clear();
        _characterToggles.Clear();

        if (state.CharacterData.Count == 0)
        {
            var noDataLabel = new Label
            {
                Text = "No contraband activity recorded this shift.",
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(10)
            };
            ContentContainer.AddChild(noDataLabel);
            return;
        }

        // Sort characters by total activity (turn-ins + registrations + sales)
        var sortedCharacters = state.CharacterData
            .OrderByDescending(kvp => kvp.Value.TotalTurnedIn + kvp.Value.TotalRegistered + kvp.Value.TotalSold)
            .ToList();

        foreach (var (characterName, data) in sortedCharacters)
        {
            var characterSection = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(5, 5, 5, 10)
            };

            // Character header with toggle button
            var headerContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal
            };

            var toggleButton = new Button
            {
                Text = "▶",
                MinWidth = 30,
                MaxWidth = 30
            };

            var headerLabel = new Label
            {
                Text = $"{characterName}",
                StyleClasses = { "LabelBig" },
                Margin = new Thickness(10, 0, 0, 0)
            };

            headerContainer.AddChild(toggleButton);
            headerContainer.AddChild(headerLabel);
            characterSection.AddChild(headerContainer);

            // Collapsible content
            var contentContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Visible = false,
                Margin = new Thickness(40, 5, 0, 0)
            };

            // Statistics grid
            var statsGrid = new GridContainer
            {
                Columns = 2,
                Margin = new Thickness(0, 5, 0, 10)
            };

            AddStatRow(statsGrid, "contraband-database-turned-in", data.TotalTurnedIn.ToString());
            AddStatRow(statsGrid, "contraband-database-registered", data.TotalRegistered.ToString());
            AddStatRow(statsGrid, "contraband-database-sold", data.TotalSold.ToString());
            AddStatRow(statsGrid, "contraband-database-scu-earned", data.ScuEarned.ToString());
            AddStatRow(statsGrid, "contraband-database-ec-earned", data.EcEarned.ToString());

            contentContainer.AddChild(statsGrid);

            // Turned in items section
            if (data.TurnedInItems.Count > 0)
            {
                var turnedInLabel = new Label
                {
                    Text = Loc.GetString("contraband-database-turned-in-items"),
                    StyleClasses = { "LabelSubText" },
                    Margin = new Thickness(0, 5, 0, 2)
                };
                contentContainer.AddChild(turnedInLabel);

                var turnedInList = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    Margin = new Thickness(10, 0, 0, 5)
                };

                foreach (var (protoId, count) in data.TurnedInItems.OrderByDescending(kvp => kvp.Value))
                {
                    var itemName = GetPrototypeName(protoId);
                    var itemLabel = new Label
                    {
                        Text = $"• {itemName}: {count}",
                        FontColorOverride = Color.LightGray
                    };
                    turnedInList.AddChild(itemLabel);
                }

                contentContainer.AddChild(turnedInList);
            }

            // Registered items section
            if (data.RegisteredItems.Count > 0)
            {
                var registeredLabel = new Label
                {
                    Text = Loc.GetString("contraband-database-registered-items"),
                    StyleClasses = { "LabelSubText" },
                    Margin = new Thickness(0, 5, 0, 2)
                };
                contentContainer.AddChild(registeredLabel);

                var registeredList = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    Margin = new Thickness(10, 0, 0, 5)
                };

                foreach (var (protoId, count) in data.RegisteredItems.OrderByDescending(kvp => kvp.Value))
                {
                    var itemName = GetPrototypeName(protoId);
                    var itemLabel = new Label
                    {
                        Text = $"• {itemName}: {count}",
                        FontColorOverride = Color.LightGray
                    };
                    registeredList.AddChild(itemLabel);
                }

                contentContainer.AddChild(registeredList);
            }

            // Sold items section
            if (data.SoldItems.Count > 0)
            {
                var soldLabel = new Label
                {
                    Text = Loc.GetString("contraband-database-sold-items"),
                    StyleClasses = { "LabelSubText" },
                    Margin = new Thickness(0, 5, 0, 2)
                };
                contentContainer.AddChild(soldLabel);

                var soldList = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    Margin = new Thickness(10, 0, 0, 5)
                };

                foreach (var (protoId, count) in data.SoldItems.OrderByDescending(kvp => kvp.Value))
                {
                    var itemName = GetPrototypeName(protoId);
                    var itemLabel = new Label
                    {
                        Text = $"• {itemName}: {count}",
                        FontColorOverride = Color.LightGray
                    };
                    soldList.AddChild(itemLabel);
                }

                contentContainer.AddChild(soldList);
            }

            characterSection.AddChild(contentContainer);

            // Wire up toggle button
            _characterSections[characterName] = contentContainer;
            _characterToggles[characterName] = toggleButton;

            toggleButton.OnPressed += _ => ToggleCharacterSection(characterName);

            ContentContainer.AddChild(characterSection);
        }
    }

    private void ToggleCharacterSection(string characterName)
    {
        if (!_characterSections.TryGetValue(characterName, out var section))
            return;

        if (!_characterToggles.TryGetValue(characterName, out var toggle))
            return;

        section.Visible = !section.Visible;
        toggle.Text = section.Visible ? "▼" : "▶";
    }

    private void AddStatRow(GridContainer grid, string labelKey, string value)
    {
        var label = new Label
        {
            Text = Loc.GetString(labelKey) + ":",
            MinWidth = 150
        };

        var valueLabel = new Label
        {
            Text = value,
            FontColorOverride = Color.LightGreen
        };

        grid.AddChild(label);
        grid.AddChild(valueLabel);
    }

    private string GetPrototypeName(string protoId)
    {
        if (_prototypeManager.TryIndex<EntityPrototype>(protoId, out var prototype))
        {
            return prototype.Name;
        }

        return protoId;
    }
}
